Add more conf files and leak check with valgrind
svn-origin-rev: 13094

diff --git a/tools/regtesting/do_regtest b/tools/regtesting/do_regtest
--- a/tools/regtesting/do_regtest
+++ b/tools/regtesting/do_regtest
@@ -103,12 +103,15 @@
 export LC_ALL=C
 export FORT_C_NAME=gfortran
 # Might consider following export to be done, too
-export MPI_F90=/gfortran
-dir_base=$HOME/cp2k/
-cp2k_version=popt
-dir_triplet=Linux-x86-64-gfortran
+export MPI_F90=mpif90
+dir_base=$PWD
+cp2k_version=sopt
+dir_triplet=Linux-x86-64-${FORT_C_NAME}
+export ARCH=${dir_triplet}
 cp2k_dir=cp2k
+numprocs=1
 maxtasks=1
+export OMP_NUM_THREADS=1
 emptycheck="NO"
 leakcheck="NO"
 
@@ -122,11 +125,9 @@ default_err_tolerance="1.0E-14"
 
 # *** how to execute an input file [ cp2k_prefix input cp2k_postfix ]
 # Leave empty for serial, uncomment for parallel
-cp2k_run_prefix="mpirun -np 2"
-#cp2k_run_prefix=""
-cp2k_run_postfix=
-#cp2k_prefix="( ulimit -t 300; ${dir_base}/${cp2k_dir}/exe/${dir_triplet}/cp2k.${cp2k_version}"
-#cp2k_postfix=" )"
+cp2k_run_prefix=""
+#cp2k_run_prefix="mpiexec -np ${numprocs}"
+cp2k_run_postfix=""
 #cp2k_prefix="poe ${dir_base}/${cp2k_dir}/exe/${dir_triplet}/cp2k.${cp2k_version}"
 #cp2k_postfix="-llfile ${dir_base}/llfile"
 
@@ -138,9 +139,7 @@ awk=awk
 
 # *** a short and long version of the data, in a format that SVN understands
 datum_full=`date --iso-8601="seconds"`
-datum_short=`date --iso-8601="seconds"`
-#datum_full=`date '+%Y-%m-%dT%H:%M:%S+0100'`
-#datum_short=`date '+%Y-%m-%d'`
+datum_short=`date '+%F_%H-%M-%S'`
 
 # *** default settings for command line switches
 quick="noquick"
@@ -163,38 +162,50 @@ svndate="$datum_full"
 #
 ###################################################################################
 while [ $# -ge 1 ]; do
-case $1 in
-  # build a list of directories to skip
-  -skipdir) let ndirstoskip=ndirstoskip+1;
-        skip_dirs[ndirstoskip]=$2;
-        shift;
-        ;;
-  # build a list of directories to restrict, i.e. only matching dirs will be run 
-  -restrictdir) let ndirstorestrict=ndirstorestrict+1;
-        restrict_dirs[ndirstorestrict]=$2;
-        shift;
-        ;;
-  # enable partial testing of only those directories that contain failed tests
-  -retest) doretest="yes";
-        shift;
-        ;; 
+ case $1 in
+ # build a list of directories to skip
+ -skipdir)
+  let ndirstoskip=ndirstoskip+1
+  skip_dirs[ndirstoskip]=$2
+  shift;;
+ # build a list of directories to restrict, i.e. only matching dirs will be run 
+ -restrictdir)
+  let ndirstorestrict=ndirstorestrict+1
+  restrict_dirs[ndirstorestrict]=$2
+  shift;;
+ # enable partial testing of only those directories that contain failed tests
+ -retest)
+  doretest="yes";;
  # load system-specific configuration
-  -config)
-        source $2 || { echo "Error loading configuration from $2" ; exit 1 ; }
-        shift
-        ;;
-  # do not update the SVN 
-  -nosvn) nosvn="nosvn";;
-  # do not reset reference outputs
-  -noreset) noreset="noreset";;
-  # do not do a realclean before building
-  -quick) quick="quick";;
-  # specify the full string "-D 2005-02-01" to get a check-out of a specific date
-  -svndate) svndate=$2; shift;;
-  -noemptycheck) emptycheck="NO";;
-  *)  break;;
-esac
-shift
+ -c|-config)
+  [[ -f $2 ]] || { echo "ERROR: Configuration file $2 not found"; exit 1; }
+  source $2   || { echo "ERROR: Sourcing of the configuration file $2 failed" ; exit 1; }
+  shift;;
+ # do not update the SVN 
+ -nosvn)
+  nosvn="nosvn";;
+ # do not reset reference outputs
+ -noreset)
+  noreset="noreset";;
+ # do not do a realclean before building
+ -quick)
+  quick="quick";;
+ # specify the full string "-D 2005-02-01" to get a check-out of a specific date
+ -svndate)
+  svndate=$2
+  shift;;
+ -noemptycheck)
+  emptycheck="NO";;
+ # stop on invalid flag
+ -*)
+  echo "ERROR: Invalid command line flag $1 found"
+  exit 1;;
+ # Default case
+ *)
+  echo "ERROR: Unknown command line string $1 found"
+  exit 1;;
+ esac
+ shift
 done
 
 if [ "${ARCH}" ]; then
@@ -207,8 +218,8 @@ fi
 cp2k_prefix=${cp2k_prefix:-"${cp2k_run_prefix} ${dir_base}/${cp2k_dir}/exe/${dir_triplet}/cp2k.${cp2k_version}"}
 cp2k_postfix=${cp2k_postfix:-"${cp2k_run_postfix}"}
 
-# allow the config file to set the maximum allowed time. Useful for valgrinded runs
-job_max_time=${job_max_time:-"300"}
+# allow the config file to set the maximum allowed time. Useful for valgrind runs
+job_max_time=${job_max_time:-"600"}
 
 ###################################################################################
 #
@@ -309,9 +320,9 @@ if [[ ${nosvn} != "nosvn" ]]; then
   cd ${dir_base}/${cp2k_dir}/src
  
   # If ChangeLog does not exist for the first time, it is created 
-  if [[ ! -s ${dir_last}/ChangeLog ]]  
-  then
-  ${dir_base}/${cp2k_dir}/tools/svn2cl/svn2cl.sh -i -o ${dir_last}/ChangeLog 
+  if [[ ! -s ${dir_last}/ChangeLog ]]; then
+     echo "Creating ChangeLog file for the first time. This may take a while ..."
+     ${dir_base}/${cp2k_dir}/tools/svn2cl/svn2cl.sh -i -o ${dir_last}/ChangeLog 
   fi
 
   svn update -r {${svndate}} &> out
@@ -329,7 +340,7 @@ if [[ ${nosvn} != "nosvn" ]]; then
   cp2k_lines=`wc *.F | tail -1 |  ${awk} '{print $1}'`
   echo "cp2k is now ${cp2k_lines} lines .F"
   
-  # *** using svn2cl.pl to generate GNU like changlelog
+  # *** using svn2cl.pl to generate GNU like changelog
   ${dir_base}/${cp2k_dir}/tools/svn2cl/svn2cl.sh --limit 100 -i -o ChangeLog.new &> out
   
   line1="$(head -n 1 ${dir_last}/ChangeLog)"
@@ -353,9 +364,9 @@ if [[ ${nosvn} != "nosvn" ]]; then
   # *** svn update test 
   cd ${dir_base}/${cp2k_dir}/tests
   
-  if [[ ! -s ${dir_last}/ChangeLog-tests ]]  
-  then
-  ${dir_base}/${cp2k_dir}/tools/svn2cl/svn2cl.sh -i -o ${dir_last}/ChangeLog-tests
+  if [[ ! -s ${dir_last}/ChangeLog-tests ]]; then
+     echo "Creating ChangeLog-tests file for the first time. This may take a while ..."
+     ${dir_base}/${cp2k_dir}/tools/svn2cl/svn2cl.sh -i -o ${dir_last}/ChangeLog-tests
   fi
 
   svn update -r {${svndate}} &> out
@@ -431,8 +442,10 @@ fi
 
 # *** from here failures are likely to be bugs in cp2k
 echo "-------------------------compiling cp2k-----------------------------------"
+echo "${make} -j $((maxtasks)) ${ARCH_SPEC} VERSION=${cp2k_version}"
+echo "(make output is written to ${cp2k_dir}/makefiles/out)"
 cd ${dir_base}/${cp2k_dir}/makefiles
-${make} -j ${maxtasks} ${ARCH_SPEC} VERSION=${cp2k_version} &> out
+${make} -j $((maxtasks)) ${ARCH_SPEC} VERSION=${cp2k_version} &> out
 if (( $? )); then
 echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >> ${error_description_file}
 tail -40 out >> ${error_description_file}
@@ -442,7 +455,7 @@ cat "${error_description_file}"
 end_test 4
 else
 compile_warnings=`grep "Warning:" out | wc | tail -1 |  ${awk} '{print $1}'`
-echo "make VERSION=${cp2k_version} went fine (${compile_warnings} warnings)"
+echo "${make} -j $((maxtasks)) ${ARCH_SPEC} VERSION=${cp2k_version} went fine (${compile_warnings} warnings)"
 fi
 echo "-------------------------regtesting cp2k----------------------------------"
 
@@ -503,8 +516,7 @@ last_test_dir=""
 retest_dirs=""
 if [[ $doretest == "yes" ]];
 then
-  last_test_dir=`ls ${dir_base} | grep ^TEST-${dir_triplet}-${cp2k_version}-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9][+-][0-9][0-9][0-9][0-9] | tail -2 | head -1`
-  
+  last_test_dir=`ls ${dir_base} | grep ^TEST-${dir_triplet}-${cp2k_version}- | tail -2 | head -1`
   if [[ "${dir_out}" == "${dir_base}/${last_test_dir}" ]]
   then
     echo "No TEST directory with latest test results found. Nothing to test!" 
@@ -572,8 +584,10 @@ rm -f ${dir_out}/status/REGTEST_RUNNING-* \
     ${dir_out}/status/REGTEST_TASK_TESTS-*
 
 
-for dir in ${dirs};
-do
+(( ndir = $(echo ${dirs} | wc -w) ))
+(( idir = 0 ))
+for dir in ${dirs}; do
+ (( idir++ ))
  #
  # tests in different dirs can run in parallel. We spawn processes up to a given maximum
  #
@@ -607,8 +621,8 @@ do
   #
   # run the tests now
   #
-  echo "Starting tests in ${dir_out}/tests/${dir}"
-  echo ">>>>>>>>>>>>>>>>> ${dir_out}/tests/${dir}" > ${dir_out}/status/REGTEST_TASK_TESTS-$task
+  echo "Starting tests in ${dir_out}/tests/${dir} (${idir} of ${ndir})"
+  echo ">>> ${dir_out}/tests/${dir}" > ${dir_out}/status/REGTEST_TASK_TESTS-$task
   ntest=`grep -v "#" TEST_FILES | ${awk} '{c=c+1}END{print c}'`
   t1=`date +%s`
   for ((itest=1;itest<=ntest;itest++));
@@ -674,25 +688,33 @@ do
      case ${this_test} in
      "NEW" )
         cp ${output_file} ${output_last} 
-        timing=`grep -a "CP2K   " ${output_file} | tail -n 1 | ${awk} '{printf("%6.2f",$NF)}'`
+        timing=`grep -a "CP2K   " ${output_file} | tail -n 1 | ${awk} '{printf("%7.2f",$NF)}'`
         this_test="${this_test} (${timing} sec)" ;;
      "OK" )
-        timing=`grep -a "CP2K   " ${output_file} | tail -n 1 | ${awk} '{printf("%6.2f",$NF)}'`
+        timing=`grep -a "CP2K   " ${output_file} | tail -n 1 | ${awk} '{printf("%7.2f",$NF)}'`
         this_test="${this_test} (${timing} sec)" ;;
      esac
      if [[ ${leakcheck} == "YES" ]]; then
-        dum=`grep -l "Remaining memory" ${output_file}`
+        if [[ -n $(echo ${cp2k_prefix} | grep "valgrind") ]]; then
+           leak_error_string="ERROR SUMMARY:"
+           nerror=$(grep -i "${leak_error_string}" ${output_file} | awk '{print $4}')
+           dum=""
+           (( nerror > 0 )) && dum=${nerror}
+        else
+           leak_error_string="Remaining memory"
+           dum=`grep -l "${leak_error_string}" ${output_file}`
+        fi
         if [[ ${dum} != "" ]]; then
-           this_test="${this_test} !"          
+           this_test="${this_test} !"
            echo "XXXXXXXX  ${output_file} XXXXXXX" >> ${memory_description_file}
-           grep -i "Remaining memory"  ${output_file} >> ${memory_description_file}
+           grep -i "${leak_error_string}" ${output_file} >> ${memory_description_file}
         fi
      fi 
-     printf "%50s %20s\n" "${dir}/${input_file}" "${this_test}" >> ${dir_out}/status/REGTEST_TASK_TESTS-$task
+     printf "    %-50s %20s\n" "${input_file}" "${this_test}" >> ${dir_out}/status/REGTEST_TASK_TESTS-$task
   done
   t2=`date +%s`
   timing_all=`echo "1+($t2)-($t1)" | bc -l`
-  printf "%s %8.2f %s\n" "<<<<<<<<<<<<<<<<< ${dir_out}/tests/${dir}" ${timing_all} "sec"  >> ${dir_out}/status/REGTEST_TASK_TESTS-$task
+  printf "%s %0.2f %s\n" "<<< ${dir_out}/tests/${dir} (${idir} of ${ndir}) done in" ${timing_all} "sec"  >> ${dir_out}/status/REGTEST_TASK_TESTS-$task
   echo "${n_runtime_error} ${n_wrong_results} ${n_correct} ${n_new} ${n_tests}" > ${dir_out}/status/REGTEST_TASK_RESULT-$task
   cat ${dir_out}/status/REGTEST_TASK_TESTS-$task
   rm -f ${dir_out}/status/REGTEST_TASK_TESTS-$task ${dir_out}/status/REGTEST_RUNNING-$task
@@ -702,7 +724,7 @@ do
  # here we allow only a given maximum of tasks
  #
  runningtasks=10000
- while (( runningtasks >= maxtasks ))
+ while (( runningtasks >= maxtasks/(numprocs*OMP_NUM_THREADS) ))
  do
    # sleep 1
    runningtasks=`ls -1 ${dir_out}/status/REGTEST_RUNNING-* 2> /dev/null | awk 'BEGIN{c=0}{c=c+1}END{print c}'`
