integrate checking for valgrind errors in the do_regtest script, i.e. they lead to a fail.
svn-origin-rev: 14543

diff --git a/tools/regtesting/do_regtest b/tools/regtesting/do_regtest
--- a/tools/regtesting/do_regtest
+++ b/tools/regtesting/do_regtest
@@ -721,6 +721,15 @@ for dir in ${dirs}; do
      output_last=${dir_last}/${dir}/${input_file}.out
      ( ulimit -t ${job_max_time} ; ${cp2k_prefix} ${input_file} ${cp2k_postfix} &> ${output_file} ) >& /dev/null
      (( cp2k_exit_status = $? ))
+     # check if this was a valgrinded run, and adjust exit status as needed
+     grep -a "^==[0-9][0-9]*== ERROR SUMMARY" ${output_file} &> /dev/null
+     if (( $? == 0 )); then
+        grep -a "^==[0-9][0-9]*== ERROR SUMMARY: 0 errors from 0 contexts" ${output_file} &> /dev/null
+        # nonzero error count
+	if (( $? )); then
+           cp2k_exit_status=42
+        fi
+     fi
      if (( cp2k_exit_status )); then
         # CP2K failed obviously
         if (( cp2k_exit_status == 137 )); then
@@ -734,6 +743,8 @@ for dir in ${dirs}; do
         echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >>${error_description_file}
         echo ${output_file} >>${error_description_file}
         tail -40 ${output_file} >>${error_description_file}
+        # append an eventual valgrind report to the file
+        grep "^==[0-9][0-9]*== " ${output_file} | head -n 20 >> ${error_description_file}
         echo "EXIT CODE: " $cp2k_exit_status " MEANING: " $this_test >>${error_description_file}
         echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >>${error_description_file}
         n_runtime_error=$((n_runtime_error+1))
@@ -744,7 +755,9 @@ for dir in ${dirs}; do
         if (( $? )); then
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >>${error_description_file}
            echo ${output_file} >>${error_description_file}
-           tail -40 ${output_file} >>${error_description_file}
+           tail -n 40 ${output_file} >>${error_description_file}
+           # append an eventual valgrind report to the file
+           grep "^==[0-9][0-9]*== " ${output_file} | head -n 20 >> ${error_description_file}
            echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" >>${error_description_file}
            this_test="RUNTIME FAIL"
            n_runtime_error=$((n_runtime_error+1))
