Fall back to a full copy of the data directory if symlinking fails (e.g. due to the execution directory living on a different filesystem)
svn-origin-rev: 14484

diff --git a/tools/regtesting/do_regtest b/tools/regtesting/do_regtest
--- a/tools/regtesting/do_regtest
+++ b/tools/regtesting/do_regtest
@@ -566,18 +566,24 @@ n_new=0
 printf "Copying tests into working directory ... "
 
 # Copy the tests into the working regtest directory.
-  cp -al ${dir_base}/${cp2k_dir}/tests ${dir_out}/tests || \
-  cp -rpl ${dir_base}/${cp2k_dir}/tests ${dir_out}/tests || ( \
-      echo "Could not copy testing directory as hard links."
-      echo "Using normal copy instead."
-      sleep 10
-      cp -rp ${dir_base}/${cp2k_dir}/tests/* ${dir_out}/tests
-  )
+cp -al ${dir_base}/${cp2k_dir}/tests ${dir_out}/tests || \
+cp -rpl ${dir_base}/${cp2k_dir}/tests ${dir_out}/tests || ( \
+  echo "Could not copy testing directory as hard links."
+  echo "Using normal copy instead."
+  sleep 10
+  cp -rp ${dir_base}/${cp2k_dir}/tests/* ${dir_out}/tests
+)
 
 printf "done!\n"
 
-printf "Creating symbolic link of data directory ... "
-ln -s ${dir_base}/${cp2k_dir}/data ${dir_out}/data
+printf "Copying data into working directory ... "
+cp -al ${dir_base}/${cp2k_dir}/data ${dir_out}/data || \
+cp -rpl ${dir_base}/${cp2k_dir}/data ${dir_out}/data || ( \
+  echo "Could not copy data directory as hard link"
+  echo "Using normal copy instead."
+  sleep 10
+  cp -rp ${dir_base}/${cp2k_dir}/data/* ${dir_out}/data
+)
 printf "done!\n"
 
 #
