Makefile: re-use REVISION to allow override, warn user
fixes #694 by warning the user via stderr and by allowing to override
the revision by setting REVISION explicitly as a `make` argument (the
warnings will still be shown since GNU make seems to execute the shell
commands prior to determining whether it is needed at all, but that is
somewhat intentional)

diff --git a/tools/build_utils/get_revision_number b/tools/build_utils/get_revision_number
--- a/tools/build_utils/get_revision_number
+++ b/tools/build_utils/get_revision_number
@@ -16,6 +16,7 @@ GIT_HEAD="${GIT_DIR}/HEAD"
 
 if [ ! -s "${GIT_HEAD}" ] ; then
   echo "<unknown revision>"
+  >&2 echo "WARNING: $0 failed to determine the Git commit and no REVISION file available"
   exit 1
 fi
 
