make_cp2k.sh: add option for performance test run (#5706)

diff --git a/tools/docker/Dockerfile.test_spack_performance-openmp b/tools/docker/Dockerfile.test_spack_performance-openmp
--- a/tools/docker/Dockerfile.test_spack_performance-openmp
+++ b/tools/docker/Dockerfile.test_spack_performance-openmp
@@ -1,6 +1,6 @@
 #
 # This file was created by generate_dockerfiles.py.
-# Usage: ./spack_cache_start.sh; podman build --shm-size=1g -t spack_pdbg -f ./Dockerfile.test_spack_pdbg ../../
+# Usage: ./spack_cache_start.sh; podman build --shm-size=1g -t spack_performance-openmp -f ./Dockerfile.test_spack_performance-openmp ../../
 #
 
 ARG BASE_IMAGE="ubuntu:26.04"
@@ -38,7 +38,7 @@ RUN apt-get update -qq && apt-get install -qq --no-install-recommends \
     && rm -rf /var/lib/apt/lists/*
 
 ARG IMAGE_TAG
-ENV IMAGE_TAG=${IMAGE_TAG:-spack_pdbg}
+ENV IMAGE_TAG=${IMAGE_TAG:-spack_performance-openmp}
 
 ARG SPACK_CACHE
 ENV SPACK_CACHE="${SPACK_CACHE:-s3://spack-cache --s3-endpoint-url=http://host.containers.internal:9000}"
@@ -48,7 +48,7 @@ WORKDIR /opt/cp2k
 COPY ./tools/spack ./tools/spack
 COPY ./tools/docker ./tools/docker
 COPY ./make_cp2k.sh .
-RUN ./make_cp2k.sh -bd_only -cv pdbg -gpu none  -mpi mpich -ue 
+RUN ./make_cp2k.sh -bd_only -cv psmp -gpu none  -mpi mpich -ue 
 
 ###### Stage 2: Build CP2K ######
 
@@ -61,7 +61,7 @@ COPY ./cmake ./cmake
 COPY ./CMakeLists.txt .
 COPY ./CMakePresets.json .
 
-RUN ./make_cp2k.sh -cv pdbg  -gpu none -mpi mpich 
+RUN ./make_cp2k.sh -cv psmp  -gpu none -mpi mpich 
 
 ###### Stage 3: Install CP2K ######
 
@@ -99,8 +99,8 @@ COPY ./tools/docker/scripts/plot_performance.py ./tools/docker/scripts/
 COPY --from=build_cp2k /etc/ld.so.conf.d/cp2k.conf /etc/ld.so.conf.d/cp2k.conf
 RUN ldconfig
 
-# Run CP2K regression test
-RUN /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_tests  || echo "ERROR: Regression test run failed"
+# Run CP2K performance test
+RUN /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_benchmarks openmp || echo "ERROR: Performance test run failed"
 
 # Create entrypoint and finalise container build
 WORKDIR /mnt
diff --git a/tools/docker/Dockerfile.test_spack_psmp-opensuse b/tools/docker/Dockerfile.test_spack_psmp-opensuse
--- a/tools/docker/Dockerfile.test_spack_psmp-opensuse
+++ b/tools/docker/Dockerfile.test_spack_psmp-opensuse
@@ -84,12 +84,20 @@ COPY --from=build_cp2k /opt/cp2k/src/grid/sample_tasks ./src/grid/sample_tasks
 # Install CP2K/Quickstep CI benchmarks
 COPY ./benchmarks/CI ./benchmarks/CI
 
+# Install benchmark inputs for performance test
+COPY ./benchmarks/QS ./benchmarks/QS
+COPY ./benchmarks/QS_reference ./benchmarks/QS_reference
+COPY ./benchmarks/QS_single_node ./benchmarks/QS_single_node
+COPY ./benchmarks/QMMM_MQAE ./benchmarks/QMMM_MQAE
+RUN mkdir -p ./tools/docker/scripts
+COPY ./tools/docker/scripts/plot_performance.py ./tools/docker/scripts/
+
 # Do not rely only on LD_LIBRARY_PATH because it is fragile
 COPY --from=build_cp2k /etc/ld.so.conf.d/cp2k.conf /etc/ld.so.conf.d/cp2k.conf
 RUN ldconfig
 
 # Run CP2K regression test
-RUN /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_tests --keepalive || echo "ERROR: Tests failed"
+RUN /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_tests --keepalive || echo "ERROR: Regression test run failed"
 
 # Create entrypoint and finalise container build
 WORKDIR /mnt
