Provide CI-compatible messages

diff --git a/tools/docker/Dockerfile.test_spack_pdbg-rawhide b/tools/docker/Dockerfile.test_spack_pdbg-rawhide
--- a/tools/docker/Dockerfile.test_spack_pdbg-rawhide
+++ b/tools/docker/Dockerfile.test_spack_pdbg-rawhide
@@ -85,7 +85,7 @@ COPY --from=build_cp2k /etc/ld.so.conf.d/cp2k.conf /etc/ld.so.conf.d/cp2k.conf
 RUN ldconfig
 
 # Run CP2K regression test
-RUN ( /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_tests --keepalive | tee /opt/cp2k/install/regression_cp2k.log ) || echo "ERROR: Regression test run failed"
+RUN ( /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_tests --keepalive || echo -e "\nSummary: Regression test run failed\nStatus: FAILED" ) 2>&1 | tee report.log
 
 # Create entrypoint and finalise container build
 WORKDIR /mnt
diff --git a/tools/docker/Dockerfile.test_spack_performance-openmp b/tools/docker/Dockerfile.test_spack_performance-openmp
--- a/tools/docker/Dockerfile.test_spack_performance-openmp
+++ b/tools/docker/Dockerfile.test_spack_performance-openmp
@@ -102,7 +102,7 @@ RUN mkdir -p ./tools/docker/scripts
 COPY ./tools/docker/scripts/plot_performance.py ./tools/docker/scripts/
 
 # Run CP2K performance test
-RUN ( /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_benchmarks openmp | tee /opt/cp2k/install/performance_cp2k.log ) || echo "ERROR: Performance test run failed"
+RUN ( /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_benchmarks openmp || echo -e "\nSummary: Performance test run failed\nStatus: FAILED" ) 2>&1 | tee report.log
 
 # Create entrypoint and finalise container build
 WORKDIR /mnt
