Adapt parallel installation to Spack 1.2
In Spack 1.2, "-j/--jobs" controls the **total** number of parallel jobs.

diff --git a/tools/docker/Dockerfile.test_spack_ssmp-static b/tools/docker/Dockerfile.test_spack_ssmp-static
--- a/tools/docker/Dockerfile.test_spack_ssmp-static
+++ b/tools/docker/Dockerfile.test_spack_ssmp-static
@@ -3,7 +3,7 @@
 # Usage: ./spack_cache_start.sh; podman build --shm-size=1g -t spack_ssmp-static -f ./Dockerfile.test_spack_ssmp-static ../../
 #
 
-ARG BASE_IMAGE="ubuntu:24.04"
+ARG BASE_IMAGE="ubuntu:26.04"
 
 ###### Stage 1: Build CP2K dependencies ######
 
@@ -48,7 +48,7 @@ WORKDIR /opt/cp2k
 COPY ./tools/spack ./tools/spack
 COPY ./tools/docker ./tools/docker
 COPY ./make_cp2k.sh .
-RUN ./make_cp2k.sh -bd_only -cv ssmp-static -gpu none -gv 14 -mpi no  
+RUN ./make_cp2k.sh -bd_only -cv ssmp-static -gpu none -mpi no  
 
 ###### Stage 2: Build CP2K ######
 
@@ -60,7 +60,7 @@ COPY ./tools/build_utils ./tools/build_utils
 COPY ./cmake ./cmake
 COPY ./CMakeLists.txt .
 
-RUN ./make_cp2k.sh -cv ssmp-static -gv 14 -gpu none -mpi no 
+RUN ./make_cp2k.sh -cv ssmp-static -gpu none -mpi no 
 
 ###### Stage 3: Install CP2K ######
 
@@ -91,7 +91,7 @@ COPY --from=build_cp2k /etc/ld.so.conf.d/cp2k.conf /etc/ld.so.conf.d/cp2k.conf
 RUN ldconfig
 
 # Run CP2K regression test
-RUN /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_tests --keepalive || echo "ERROR: Tests failed"
+RUN /opt/cp2k/install/bin/launch /opt/cp2k/install/bin/run_tests || echo "ERROR: Tests failed"
 
 # Create entrypoint and finalise container build
 WORKDIR /mnt
